### ISSUE TITLE
Backend Authentication Password Error and Missing Server-Side Validation (PRIORITY)

### ISSUE THREAD

**Issue by DebdipWritesCode** [harshalhonde21/EcommerceSpectastyle#62] opened 2024-05-10 17:37 UTC
### Description

When a new user is signing up, an error pops up saying "Signup failed, please check your credentials." At a glance, there's no definite cause of why this error is happening but after doing some console.log statements, I found out the issue. The issue is that if an user tries to use a password that has already been used by someone else, he won't be able to signup with that same password. This is a big fault since users should be able to login with any password they want.

### Visuals

 #![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/151666336/11f75698-1c6e-41c7-ac34-d73c7150e2e2)
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/151666336/84878ce3-1832-49ff-8c25-e5e73057a039)

**The error produced on the backend side:** 
![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/151666336/a4355bd0-1fcd-4f5e-80f0-5b67cc444abb)

### How to Reproduce?

Go to Signup page and try to signup with an already used password like "Potato1234"

### Expected Behavior

Successful login by user

### Actual Behavior

Unable to signup error along with a 500 status code response from the backend server

### Additional Issues

- No server side validation for signing up and logging in
- Bycrypt is called but password is not hashed before storing which raises security concerns if database is compromised
- MongoDB database needs to be revamped since there are too many unordered collections
- Auth Middleware is made but never used in Routes/user-routes.js

Overall, I would say that the backend needs some good amount of work and I would be very happy to help you solve this issues. Please consider me for fixing this issue. Thanks :)

**Comment by niteshtiwari52** [comment] 2024-05-10 17:57
I want to fix this issue. Could you please asssign me this issue??

**Comment by harshalhonde21** [comment] 2024-05-10 17:58
Go, with this issue but create whole documentation before raising the PR

**Comment by niteshtiwari52** [comment] 2024-05-10 17:59
For Documentation any format is already exsist ?? 
OR I can share only Postman Documentation ??

**Comment by niteshtiwari52** [comment] 2024-05-10 18:02
@harshalhonde21
It was not assigned to me ??

**Comment by niteshtiwari52** [comment] 2024-05-10 18:09
I am so sorry,  this issue was already opened by another contributer. By mistakely I commented on others issue. 

Sorry for inconvenience caused by me.

**Comment by officeneerajsaini** [comment] 2024-05-11 05:05
@harshalhonde21 assign this issue to me i will this issue much better , [Auth](https://registration-form-4ylp.onrender.com/)  this repo made by me you can check my work .

**Comment by swataswayam-14** [comment] 2024-05-11 07:34
@harshalhonde21  I believe I can contribute to a swift resolution. I've previously tackled similar bugs and confident in my ability to fix this effectively.

**Closed** 2024-05-12 12:49 UTC
Labels: enhancement, Level 2, gssoc
